### ISSUE TITLE
CRM integration - Mockups

### ISSUE THREAD

**Issue by darshi-shah** [saurabhd/hk_realestate#19]
Mockups for CRM goes here

**Comment by darshi-shah** [comment]
Hi Rainer,

Please provide your feedback for this mockups.

Thanks
Darshi

![contact](https://cloud.githubusercontent.com/assets/15724372/15896886/d56bfd38-2daf-11e6-8447-d86b8d324a0d.png)
![dashboard](https://cloud.githubusercontent.com/assets/15724372/15896887/d57c6236-2daf-11e6-864e-6345045b1e41.png)

**Comment by heliogabal** [comment]
I love it, looks great, good work. I sent it to the client to get his feedback, but I think the direction is very good. Nice clean modern interface matching the client's CI.

Some small things would need to be decided, but I think it's best to wait for the clients feedback as well.
I personally would prefer red and black over red and blue (my anarchist soul...), think that white background for the dashboard would be more focused (but it's good to have the variation to show), would like to try completely flat for the table headers.

Then, a free text field for the search criteria is missing, and we wouldn't need a for rent price on the matching apartments (there are only aparts to buy on the site). That's about it... :-)

I like the icons a lot, we should definitely work with those to help support efficient work. I assume those would get standardized and we should find the perfect set for the final product... 

Where would we get buyers photos from? I think we can get the profile pics if they log in via social media, but probably a majority won't do that and log in the old school way. Is there another way (module?) to get those from the open net? Gravatar never really took off for the masses, I think. At least we would need to provide different placeholders for the ones without pic, otherwise the visual clue is misleading.

If I look at it, I'm not sure if we need the Activity ID column at all. Maybe we could use the space that's won by that for a thumbnail of the apartment inquired about, to have another visual clue?

**Comment by heliogabal** [comment]
client has personal isssues preventing him from giving feedback soon, but gave ok to go on with it as we see fit.

**Comment by darshi-shah** [comment]
Hi Rainer,

Attached are revised mockups.

Thanks
Darshi
[Updated Mockups.zip](https://github.com/saurabhd/hk_realestate/files/310125/Updated.Mockups.zip)

**Comment by heliogabal** [comment]
![1](https://cloud.githubusercontent.com/assets/389844/16002575/c185d3aa-3158-11e6-8e27-52a09067fe1b.jpg)

![3](https://cloud.githubusercontent.com/assets/389844/16002578/c760dd38-3158-11e6-82e2-ee454d2ba02a.jpg)

**Comment by darshi-shah** [comment]
Hi Rainer,

Please provide your feedback for this mockup.

![pasted image at 2016_06_29 07_15 pm](https://cloud.githubusercontent.com/assets/15724372/16454531/bea327f4-3e2e-11e6-8bcc-781303e1bcb2.png)

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer,

Please find attached revised mockup for agent central. Let us know your feedback for same.

Thanks,
Darshi

![agent-central](https://cloud.githubusercontent.com/assets/15724372/16520923/1f3affc8-3fb1-11e6-9a4d-563e640a6140.png)

**Comment by heliogabal** [comment]
Hi Darshi,
looking good! I wonder if we can use flags to mark to-dos as completed, so they disappear from the list once they're flagged? Depending on the size of the to-do description, we would maybe need another + to expand the full description.

And it seems logical to me to have a link from the My contacts Name field to the contact page.

Apart from that, everything's fine!
