### ISSUE TITLE
CRM - finishing touches Contact Page

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#24]
Here are some (hopefully) minor things to polish the contact page: 
- Address formating: the standard addressfield format is missing spaces and commas and doesn't look good, the Country is not really necessary. Fastest solution with an additional module would be addressfield_tokens, there's an issue with a patch and code based solution as well: https://www.drupal.org/node/1541384
- If no Birthday is set, it defaults to 01.01 which could lead to problems once we implement automatic birthday congratulations. Should be empty if not set. I have a birthday set for contact 11 (18.05.1976), but it only shows as 01.01.
- Not sure if the other Titles should be shown if not set (Languages, Other). Probably just don't show them if empty.
- Please use another standard avatar picture - it's disturbing to see myself all the time ;-) 
- The show notes row pushes the first to the right. It's minor, but disorienting. Some max-width should help.
- Dates in the activity table are m.d.Y, should be d.m.Y for German eyes.
- Notes Tab: Not sure what to do with a notes title. Either autocreate standard title and don't show it, or let the user fill the title and show it in the Note view cell as well. Date can be short form d.m.Y - H:I
- Favorites Tab: Not sure if this is because of missing contact - user sync, but as user rainer, I have 2 favorites that don't show on the favorites tab.
- I could change the Search Criteria Title into German, but haven't found where the Matching Apartments/Similar properties are set.
- Create Contact and Create Activity have to be translatable, or at least in German for now: Kontakt erstellen and Aktivität erstellen, but that is too long for the fixed width of the button.
- I translated the activities, but they still show in English under Create activity. Same as with the buttons: should be transaltable or at least in German.
- Matching Apartments: m² don't need ,00. For rooms, I only see the icon. The price should be having a space as thousands seperator.

**Comment by darshi-shah** [comment]
Hi Rainer,

Code is pushed in "hkcrm" branch. You need to revert hk_crm feature.
1. Address formating: the standard addressfield format is missing spaces and commas and doesn't look good, the Country  is not really necessary. Fastest solution with an additional module would be addressfield_tokens, there's an issue with a patch and code based solution as well: https://www.drupal.org/node/1541384 
   => Done
2. If no Birthday is set, it defaults to 01.01 which could lead to problems once we implement automatic birthday congratulations. Should be empty if not set. I have a birthday set for contact 11 (18.05.1976), but it only shows as 01.01.
   => Done
3. Not sure if the other Titles should be shown if not set (Languages, Other). Probably just don't show them if empty.
   => Done
4. Please use another standard avatar picture - it's disturbing to see myself all the time ;-)
   => As following set to default image.
   -> Go to admin/structure/crm-core/contact-types/manage/individual/fields/field_profile_picture.
   -> Remove Default image and set new image send by me.(http://spiderimg.amarujala.com/assets/img/default_user.jpg)
5. The show notes row pushes the first to the right. It's minor, but disorienting. Some max-width should help.
   => Done
6. Dates in the activity table are m.d.Y, should be d.m.Y for German eyes.
   => Done(Set d.m.Y for all languages)
7. Notes Tab: Not sure what to do with a notes title. Either autocreate standard title and don't show it, or let the user fill the title and show it in the Note view cell as well. Date can be short form d.m.Y - H:I
   => Done(Display notes with node title)
8. Favorites Tab: Not sure if this is because of missing contact - user sync, but as user rainer, I have 2 favorites that don't show on the favorites tab.
   => Here favorites apartment display which flaged by contact, not user.You can flag favorite content from this:crm-core/contact/11/activity and then it will show for the specific contact.
9. I could change the Search Criteria Title into German, but haven't found where the Matching Apartments/Similar properties are set.
   => Set text in t() function so need no set from translation url.If not find text on Translation set then need visit page on non-default language and then refresh string and need clear cache.
10. Create Contact and Create Activity have to be translatable, or at least in German for now: Kontakt erstellen and Aktivität erstellen, but that is too long for the fixed width of the button.
    => Done
11. Matching Apartments: m² don't need ,00. For rooms, I only see the icon. The price should be having a space as thousands seperator.
    => Done

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
Great work! I tested, and everything is fine, except some minor issues: 
- First name and last name should be switched (Rainer Halbmann instead of Halbmann Rainer). That's more common in Germany.
- you have to turn on AJAX on the quicktabs views, otherwise the pagers do weird things (if you're on page two of activities, and then switch to notes, no notes are found...)
- favorites tab should also have a space as thousands separator
- Don't know if that's only because I flagged the apartment as advised by you in 8., but I get duplicates in that view. Setting the database query settings to distinct solves this, don't know if that has any side effects.

**Comment by darshi-shah** [comment]
Hi Rainer,

Code is pushed in "hkcrm" branch. You need to revert hk_crm feature.
1. First name and last name should be switched (Rainer Halbmann instead of Halbmann Rainer). That's more common in Germany.
   => Done
2. you have to turn on AJAX on the quicktabs views, otherwise the pagers do weird things (if you're on page two of activities, and then switch to notes, no notes are found...)
   => Done
3. favorites tab should also have a space as thousands separator.
   => Done
4. Don't know if that's only because I flagged the apartment as advised by you in 8., but I get duplicates in that view. Setting the database query settings to distinct solves this, don't know if that has any side effects.
   => Done

Thanks
Darshi
