### ISSUE TITLE
Explorer better search selects.

### ISSUE THREAD

**Issue by arpita-addweb** [saurabhd/hk_realestate#9]
**Site Area** : search box ,**Priority**: low

**Description** : Would it be possible that instead of the select range values (price, rooms, space), on click a slider is shown where you can select a range? So the initial design of the box shouldn't be altered, but there should be more user friendly and flexible ways of selecting ones preferences. E.g. right now, it is only possible to search for 0-2 rooms OR 2-4 rooms, not for 2-5 or 2-3. Same for price: what if I want everything that is more than 250 000€, because I don't like cheap options, or my budget is 500 000€ and I want to see all offers for that?

**Comment by darshi-shah** [comment]
Hi Rainer,

Please see http://i.share.pho.to/ec9a4887_o.png to see how ranges will look for price, rooms, space. Please note that this not done yet, we need your inputs on this.

Search filters were inside search fields. With search ranges, we will need to add labels on top so users know which range is for which filter. 

The same design will also be applied to home page search filters.

Please let us your inputs for this.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 

yeah, that's what I already tried, but the client doesn't want the element to look different. So the elements should look exactly like the select, but on click, instead of getting a list, there should be a slider. But I don't think it's the most usable solution anyway, so  I'll have to think about this some more, so for the time being, I set this to wontfix.

Thanks for looking into this
